name: Build

on:
  pull_request:
    types:
      - closed
    branches:
      - build

env:
  BUILD_PATH: src-tauri/target/release/bundle

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      # Bump version and push tag
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      new_version: ${{ steps.tag_version.outputs.new_version }}

  build:
    needs: init
    name: Build binaries
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - os: ubuntu-latest
          arch: x86_64
          rust_target: x86_64-unknown-linux-gnu
        - os: macos-latest
          arch: x86_64
          rust_target: x86_64-apple-darwin
        - os: macos-latest
          arch: aarch64
          rust_target: aarch64-apple-darwin
        - os: windows-latest
          arch: x86_64
          rust_target: x86_64-pc-windows-msvc

    steps:
      # Checkout
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '5'

    # Setups and installs dependencies
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.config.rust_target }}

    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.config.rust_target }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19.x'
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
      
    - name: Install dependencies
      run: pnpm install
      
    - name: Install dependencies (Ubuntu)
      if: matrix.config.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Build binaries
      run:  pnpm tauri build
      
    # Extract and upload artifacts to create release
    - name: Create release for AppImage
      if: matrix.config.os == 'ubuntu-latest'
      run: mv ${{ env.BUILD_PATH }}/appimage/*.AppImage ${{ env.BUILD_PATH }}/appimage/Tally-${{ needs.init.outputs.new_version }}-linux-${{ matrix.config.arch }}.AppImage
    - uses: ncipollo/release-action@v1.12.0
      with:
        name: ${{ needs.init.outputs.new_tag }}
        tag: ${{ needs.init.outputs.new_tag }}
        artifacts: ${{ env.BUILD_PATH }}/appimage/*.AppImage
        allowUpdates: true

    - name: Create release for deb
      if: matrix.config.os == 'ubuntu-latest'
      run: mv ${{ env.BUILD_PATH }}/deb/*.deb ${{ env.BUILD_PATH }}/deb/Tally-${{ needs.init.outputs.new_version }}-linux-${{ matrix.config.arch }}.deb
    - uses: ncipollo/release-action@v1.12.0
      with:
        name: ${{ needs.init.outputs.new_tag }}
        tag: ${{ needs.init.outputs.new_tag }}
        artifacts: ${{ env.BUILD_PATH }}/deb/*.deb
        allowUpdates: true

    - name: Create release for dmg
      if: matrix.config.os == 'macos-latest'
      run: mv ${{ env.BUILD_PATH }}/dmg/*.dmg ${{ env.BUILD_PATH }}/dmg/Tally-${{ needs.init.outputs.new_version }}-macos-${{ matrix.config.arch }}.dmg
    - uses: ncipollo/release-action@v1.12.0
      with:
        name: ${{ needs.init.outputs.new_tag }}
        tag: ${{ needs.init.outputs.new_tag }}
        artifacts: ${{ env.BUILD_PATH }}/dmg/*.dmg
        allowUpdates: true
      
    - name: Create release for app
      if: matrix.config.os == 'macos-latest'
      run: mv ${{ env.BUILD_PATH }}/macos/*.app ${{ env.BUILD_PATH }}/macos/Tally-${{ needs.init.outputs.new_version }}-macos-${{ matrix.config.arch }}.app
    - uses: ncipollo/release-action@v1.12.0
      with:
        name: ${{ needs.init.outputs.new_tag }}
        tag: ${{ needs.init.outputs.new_tag }}
        artifacts: ${{ env.BUILD_PATH }}/macos/*.app
        allowUpdates: true

    - name: Create release for msi
      if: matrix.config.os == 'windows-latest'
      run: mv ${{ env.BUILD_PATH }}/msi/*.msi ${{ env.BUILD_PATH }}/msi/Tally-${{ needs.init.outputs.new_version }}-windows-${{ matrix.config.arch }}.msi
    - uses: ncipollo/release-action@v1.12.0
      with:
        name: ${{ needs.init.outputs.new_tag }}
        tag: ${{ needs.init.outputs.new_tag }}
        artifacts: ${{ env.BUILD_PATH }}/msi/*.msi
        allowUpdates: true