name: Build

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-20.04, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Install dependencies
        run: pnpm install
      
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Build binaries
        run:  pnpm tauri build

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "src-tauri/target/release/bundle/msi/*.msi, src-tauri/target/release/bundle/dmg/*.dmg, src-tauri/target/release/bundle/deb/*.deb, src-tauri/target/release/bundle/appimage/*.AppImage"
          allowUpdates: true